const shops = [
    {
        '_id': 'S-1',
        'name': 'Airpods Wireless Bluetooth Headphones',
        'image': 'arch-shop/arch-shop-images/airpods.jpg',
        'description':
          'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 89.99,
        'like': 10,
        'rating': 4.5,
        'numReviews': 12,
        'unlike': 12,
      },
      {
        '_id': 'S-2',
        'name': 'iPhone 11 Pro 256GB Memory',
        'image': 'arch-shop/arch-shop-images/phone.jpg',
        'description':
          'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 599.99,
        'like': 7,
        'rating': 4.0,
        'numReviews': 8,
        'unlike': 20,
      },
      {
        '_id': 'S-3',
        'name': 'Cannon EOS 80D DSLR Camera',
        'image': 'arch-shop/arch-shop-images/camera.jpg',
        'description':
          'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
        'brand': 'Cannon',
        'category': 'Electronics',
        'price': 929.99,
        'like': 5,
        'rating': 3,
        'numReviews': 12,
        'unlike': 1,
      },
      {
        '_id': 'S-4',
        'name': 'Sony Playstation 4 Pro White Version',
        'image': 'arch-shop/arch-shop-images/playstation.jpg',
        'description':
          'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
        'brand': 'Sony',
        'category': 'Electronics',
        'price': 399.99,
        'like': 11,
        'rating': 5,
        'numReviews': 12,
        'unlike': 18,
      },
      {
        '_id': 'S-5',
        'name': 'Logitech G-Series Gaming Mouse',
        'image': 'arch-shop/arch-shop-images/mouse.jpg',
        'description':
          'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
        'brand': 'Logitech',
        'category': 'Electronics',
        'price': 49.99,
        'like': 7,
        'rating': 3.5,
        'numReviews': 10,
        'unlike': 25,
      },
      {
        '_id': 'S-6',
        'name': 'Amazon Echo Dot 3rd Generation',
        'image': 'arch-shop/arch-shop-images/alexa.jpg',
        'description':
          'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
        'brand': 'Amazon',
        'category': 'Electronics',
        'price': 29.99,
        'like': 0,
        'rating': 4,
        'numReviews': 12,
        'unlike': 33,
      },
      {
          '_id': 'S-7',
          'name': 'Amazon Echo Dot 3rd Generation',
          'image': 'arch-shop/arch-shop-images/alexa.jpg',
          'description':
            'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
          'brand': 'Amazon',
          'category': 'Electronics',
          'price': 29.99,
          'like': 0,
          'rating': 1.5,
          'numReviews': 12,
          'unlike': 2,
        },
        {
          '_id': 'S-8',
          'name': 'Amazon Echo Dot 3rd Generation',
          'image': 'arch-shop/arch-shop-images/alexa.jpg',
          'description':
            'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
          'brand': 'Amazon',
          'category': 'Electronics',
          'price': 29.99,
          'like': 0,
          'rating': 4,
          'numReviews': 12,
          'unlike': 11,
        },
        {
          '_id': 'S-9',
          'name': 'Amazon Echo Dot 3rd Generation',
          'image': 'arch-shop/arch-shop-images/alexa.jpg',
          'description':
            'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
          'brand': 'Amazon',
          'category': 'Electronics',
          'price': 29.99,
          'like': 0,
          'rating': 2,
          'numReviews': 12,
          'unlike': 16,
        },
        {
          '_id': 'S-10',
          'name': 'Amazon Echo Dot 3rd Generation',
          'image': 'arch-shop/arch-shop-images/alexa.jpg',
          'description':
            'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
          'brand': 'Amazon',
          'category': 'Electronics',
          'price': 29.99,
          'like': 0,
          'rating': 2.5,
          'numReviews': 12,
          'unlike': 9,
        },
]

export default shops;